[refactoring] added the ability to send the notification to Telegram or Gotify Server from file config

diff --git a/wg-clients-guardian b/wg-clients-guardian
--- a/wg-clients-guardian
+++ b/wg-clients-guardian
@@ -1,35 +1,46 @@
 #!/bin/bash
+# Send a message to Telegram or Gotify Server when a client is connected or disconnected from wireguard tunnel
+#
+#
 # This script is written by Alfio Salanitri <www.alfiosalanitri.it> and are licensed under MIT License.
 # Credits: This script is inspired by https://github.com/pivpn/pivpn/blob/master/scripts/wireguard/clientSTAT.sh
-
-# config variables
-readonly CURRENT_PATH=$(pwd)
-readonly CLIENTS_DIRECTORY="$CURRENT_PATH/clients"
-readonly NOW=$(date +%s)
-
-# after X minutes the clients will be considered disconnected
-readonly TIMEOUT=15
 
 # check if wireguard exists
 if ! command -v wg &> /dev/null; then
 	printf "Sorry, but wireguard is required. Install it and try again.\n"
 	exit 1;
 fi
+
+# check if the user passed in the config file and that the file exists
+if [ ! "$1" ]; then
+	printf "The config file is required.\n"
+	exit 1
+fi
+if [ ! -f "$1" ]; then
+	printf "This config file doesn't exist.\n"
+	exit 1
+fi
+
+# config constants
+readonly CURRENT_PATH=$(pwd)
+readonly CLIENTS_DIRECTORY="$CURRENT_PATH/clients"
+readonly NOW=$(date +%s)
+
+# after X minutes the clients will be considered disconnected
+readonly TIMEOUT=$(awk -F'=' '/^timeout=/ { print $2}' $1)
+
 readonly WIREGUARD_CLIENTS=$(wg show wg0 dump | tail -n +2) # remove first line from list
 if [ "" == "$WIREGUARD_CLIENTS" ]; then
 	printf "No wireguard clients.\n"
 	exit 1
 fi
 
-# check if the user passed in the telegram config file and that the file exists
-if [ ! "$1" ]; then
-	printf "The config file with telegram chat id and bot token is required.\n"
-	exit 1
-fi
-if [ ! -f "$1" ]; then
-	printf "This telegram config file doesn't exist.\n"
-	exit 1
-fi
+readonly NOTIFICATION_CHANNEL=$(awk -F'=' '/^notification_channel=/ { print $2}' $1)
+
+readonly GOTIFY_HOST=$(awk -F'=' '/^gotify_host=/ { print $2}' $1)
+readonly GOTIFY_APP_TOKEN=$(awk -F'=' '/^gotify_app_token=/ { print $2}' $1)
+readonly GOTIFY_TITLE=$(awk -F'=' '/^gotify_title=/ { print $2}' $1)
+
 readonly TELEGRAM_CHAT_ID=$(awk -F'=' '/^chat=/ { print $2}' $1)
 readonly TELEGRAM_TOKEN=$(awk -F'=' '/^token=/ { print $2}' $1)
 
@@ -80,9 +91,14 @@ while IFS= read -r LINE; do
 	# send notification to telegram
 	if [ "no" != "$send_notification" ]; then
 		printf "The client %s is %s\n" $client_name $send_notification
-		message="🐉 Wireguard: \`$client_name is $send_notification from ip address $remote_ip\`"
-		curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" -F chat_id=$TELEGRAM_CHAT_ID -F text="$message" -F parse_mode="MarkdownV2" > /dev/null 2>&1
-	else
+		message="$client_name is $send_notification from ip address $remote_ip"
+    if [ "telegram" == "$NOTIFICATION_CHANNEL" ] || [ "both" == "$NOTIFICATION_CHANNEL" ]; then
+      curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" -F chat_id=$TELEGRAM_CHAT_ID -F text="🐉 Wireguard: \`$message\`" -F parse_mode="MarkdownV2" > /dev/null 2>&1
+    fi
+    if [ "gotify" == "$NOTIFICATION_CHANNEL" ] || [ "both" == "$NOTIFICATION_CHANNEL" ]; then
+      curl -X POST "${GOTIFY_HOST}/message" -H "accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer ${GOTIFY_APP_TOKEN}" -d '{"message": "'"$message"'", "priority": 5, "title": "'"$GOTIFY_TITLE"'"}' > /dev/null 2>&1
+    fi
+  else
 		printf "The client %s is %s, no notification will be sent.\n" $client_name $(cat $client_file)
 	fi
 
